### ISSUE TITLE
Wrong flag

### ISSUE THREAD

**Issue by bootje** [rensa/ggflags#7]
Hi @rensa,

It seems like the Latvian flag (lv) has the wrong colors. It has kind of purple stripes but these should be dark red. I tried to modify the Rdata file to fix it, but it was a bit more complicated than expected. Perhaps you can take a look at it at some point?

Thanks in advance,
Martin

**Comment by jimjam-slam** [comment]
Thanks for the heads-up, Martin! I'll look into it 🙂 I'd have to check the flag to be sure, but this likely a stylistic decision that Twemoji made. I'll look into whether I can just make a manual modification or whether I should convince them to change it upstream.

**Comment by bootje** [comment]
Hi @rensa, thanks for taking a look! I guess it would be best if it can change upstream. If not it should be enough to change to color, the size of the colored stripes seems accurate. The [correct color is #9E3039](https://www.schemecolor.com/latvia-flag-colors.php).

**Comment by jimjam-slam** [comment]
Interestingly, this flag looks correct in EmojiOne!

https://github.com/eosrei/emojione-color-font/blob/master/assets/emojione-svg/1f1f1-1f1fb.svg

It hasn't been modified since June 2016, so I'm not sure what went wrong when I originally imported the flags (using `inst/store_flags.R`).

I also need to process the flags to get rid of clipping masks in them (because it interferes with ggplot2's clipping used on the plot area: plots can only have one clipping mask at a time), so maybe I need to do a bigger PR to get all those issues at once.

**Comment by bootje** [comment]
Hi @rensa, thanks for the update, indeed weird that the flag is ok in EmojiOne. I guess it's best to combine multiple issues, it always takes some time to get familiar with things you did in the past!

**Comment by StefanMusch** [comment]
Any update on this issue? I noticed the same thing today when using this (awesome) package.

**Comment by jimjam-slam** [comment]
Sorry, I've been a little slack maintaining my packages over the break! If anyone has the time for a PR, I'm happy to review it; otherwise I'll endeavour to get to it ASAP 🙂

**Comment by N190392** [comment]
I'd like to note that the previously linked EmojiOne flag has still wrong color. As bootje mentioned, the correct color should be #9E3039.

**Comment by jimjam-slam** [comment]
I'll do another pass on this when I implement #17!
