### ISSUE TITLE
Won't install Description

### ISSUE THREAD

**Issue by cesar-galvao** [rensa/ggflags#8]
I'm using this to install ggflags:

`devtools::install_github("rensa/ggflags")`

This is the error message I get:

` √  checking for file 'C:\Users\Cesar Augusto Galvão\AppData\Local\Temp\RtmpSmDcvg\remotesb085dfc42bb\rensa-ggflags-401494a/DESCRIPTION' ...
-  preparing 'ggflags':
√  checking DESCRIPTION meta-information ... 
   Warning in .write_description(db, ldpath) :
     Unknown encoding with non-ASCII data: converting to ASCII
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'ggflags_0.0.2.tar.gz'
   
* installing *source* package 'ggflags' ...
Error in file(file, if (append) "a" else "w") : 
  (converted from warning) cannot open file 'C:/Users/Cesar Augusto Galvco/Documents/R/win-library/3.5/ggflags/DESCRIPTION': No such file or directory
ERROR: installing package DESCRIPTION failed for package 'ggflags'
* removing 'C:/Users/Cesar Augusto Galvão/Documents/R/win-library/3.5/ggflags'
In R CMD INSTALL `

I'm sorry I'm reaching out to you, I can`t seem to find anyone else having this problem.

**Comment by jimjam-slam** [comment]
Sorry for the delay getting back to you, @cesar-galvao!

My only hunch with this problem is that your Mac user name, which contains non-ASCII characters (ã), is causing package installation problems. I say this because the first part of the error says refers to your user name with the diacritic in it. Then, after the message "Unknown encoding with non-ASCII data: converting to ASCII", a path to your user folder appears _without_ the diacritic.

I think the easiest ways to test this would be to:

(a) Check whether you're able to install other packages using `devtools`. For example, `devtools::install_github('vincentarelbundock/countrycode')`, and if that doesn't work, `install.packages('countrycode')`. If the former fails but the latter succeeds, this could be a problem with `devtools`.

(b) Try creating a new Windows user whose name doesn't have a diacritic in it and installing `ggflags` for that user.
